# Generated by Django 5.1.6 on 2025-02-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_place', models.CharField(max_length=255, verbose_name='Початкова точка')),
                ('end_place', models.CharField(max_length=255, verbose_name='Кінцева точка')),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Початкова широта')),
                ('start_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Початкова довгота')),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Кінцева широта')),
                ('end_lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Кінцева довгота')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Відстань (км)')),
                ('duration', models.IntegerField(verbose_name='Тривалість (хв)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
